name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - v*

env:
  CI_REGISTRY_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Generate Docker image tag
        run: |
          if [[ ${GITHUB_REF} == refs/tags/* ]]; then
            TAG=$(echo "${GITHUB_REF}" | grep -Po 'refs/tags/v?\K.+$')
          else
            TAG=latest
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Build images from docker-compose.yml
        run: docker compose build
      - name: Push images from docker-compose.yml
        run: docker compose push
